baseurl: /
title: University Modeling Instruction
languageCode: en-us
paginate: '10'
theme: Mainroad
disqusShortname: ''
googleAnalytics: ''
Author: 
  avatar: 
  name: Eric Brewe
Params:
  authorbox: yes
  description: A site for maintaing curriculum materials for University Modeling Instruction
  header: img/welcome2.png
  logo: 
    subtitle: Curriculum Materials for University Mechanics
  mainSections:
    - home
    - curriculum by week:   
      - week One
      - week Two
    - video Index
    - faq
    - research
    - contributors
  opengraph: yes
  pager: yes
  post_meta:
    - categories
  readmore: no
  sidebar:
    home: right
    list: right
    single: right
    widgets:
      - search
      - recent
      - categories
      - taglist
  toc: true #trying
  twitter_cards: no
  widgets:
    recent_num: 5
    tags_counter: no
